osx_image: xcode10
language: swift
script:
  - set -o pipefail && xcodebuild \
    -enableCodeCoverage YES \
    -workspace Example/MuslimData.xcworkspace \
    -scheme MuslimData-Example \
    -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0' \ 
    test | xcpretty --test --color
  - pod lib lint --allow-warnings
deploy:
  provider: script
  script: ./scripts/push.sh
  on:
    tags: true
