osx_image: xcode10
language: swift
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MuslimData.xcworkspace -scheme MuslimData-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint --allow-warnings
